### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/lightlda#1]
I would like to point out that identifiers like "[`_LIGHTLDA_DATA_STREAM_H_`](https://github.com/Microsoft/lightlda/blob/42c693bda6ad75e7e70282915f102a551dc6cd4b/src/data_stream.h#L6)" and "[`_LIGHTLDA_TRAINER_H_`](https://github.com/Microsoft/lightlda/blob/f1a84ee2fb8cac7a6a034366362cc848177da808/src/trainer.h#L6)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by feiga** [comment]
Very useful comments. Thanks very much! I fixed this.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/Microsoft/lightlda/commit/aac9e7b23445e42550af8d5617c6271deb2803cc "Deletion of a few underscores").
