### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/lightlda#2]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [a function like "AliasTable::Clear"](https://github.com/Microsoft/lightlda/blob/e37c71c7ed508315bcec5faeaf22d8ad5e5ac711/src/alias_table.cpp#L161 "AliasTable::Clear function").

**Comment by feiga** [comment]
Fixed, thanks!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Microsoft/lightlda/commit/08b72a5257eab630b3689bc6c5a1fe9451dc16fa "Deletion of unnecessary null pointer checks").
