### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by ericxsun** [microsoft/LightLDA#27]
While doing dump_binary in the given example `nytimes.sh`, throw out such error: std:bad_alloc

```
bin/dump_binary example/data/nytimes/nytimes.libsvm example/data/nytimes/nytimes.word_id.dict example/data/nytimes/ 0
```

logs:

There are totally 101636 words in the vocabulary
There are maximally totally 99542125 tokens in the data set
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abort

Could anybody help me? Highly appreciated.

**Comment by feiga** [comment]
It seems there is no enough memory.

**Comment by followyourheart** [comment]
yes, I have solved it when I increased the memory. Also thanks a lot. @feiga
