### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [Microsoft/lightlda#3]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidate: [AliasTable](https://github.com/Microsoft/lightlda/blob/08b72a5257eab630b3689bc6c5a1fe9451dc16fa/src/alias_table.cpp#L17 "AliasTable class")

**Comment by feiga** [comment]
Thanks. The memory here is managed well. May consider change to smart pointer later.

**Comment by elfring** [comment]
Should this issue be kept open until [the affected implementation details](http://ootips.org/yonat/4dev/smart-pointers.html "Smart Pointers - What, Why, Which?") will be fixed?
