### ISSUE TITLE
not support inference on windows

### ISSUE THREAD

**Issue by tanglizhe1105** [Microsoft/lightLDA#36]
I use LightLDA to infer doc-topic distribution  on windows, but it doesn't work.
I find the windows part code for inference is not implemented. So, would you have a plan to add windows inference function.

https://github.com/Microsoft/lightLDA/blob/master/src/model.cpp#L3
https://github.com/Microsoft/lightLDA/blob/master/src/model.cpp#L50

**Comment by davyfeng** [comment]
same issue for me, any fix or suggestion on that?

**Comment by ruskie95** [comment]
infer.obj : error LNK2001: unresolved external symbol "public: __cdecl multiverso::lightlda::AliasTable::~AliasTable(void)" (??1AliasTable@lightlda@multiverso@@qeaa@XZ)
infer.obj : error LNK2001: unresolved external symbol "public: __cdecl multiverso::lightlda::AliasTable::AliasTable(void)" (??0AliasTable@lightlda@multiverso@@qeaa@XZ)
infer.obj : error LNK2001: unresolved external symbol "public: static bool multiverso::lightlda::Config::warm_start" (?warm_start@Config@lightlda@multiverso@@2_NA)
infer.obj : error LNK2001: unresolved external symbol "public: static int multiverso::lightlda::Config::num_iterations" (?num_iterations@Config@lightlda@multiverso@@2ha)
infer.obj : error LNK2001: unresolved external symbol "public: void __cdecl multiverso::lightlda::LocalModel::Init(void)" (?Init@LocalModel@lightlda@multiverso@@qeaaxxz)
infer.obj : error LNK2001: unresolved external symbol "public: __cdecl multiverso::lightlda::LocalModel::LocalModel(class multiverso::lightlda::Meta *)" (??0LocalModel@lightlda@multiverso@@qeaa@PEAVMeta@12@@z)
infer.obj : error LNK2001: unresolved external symbol "public: static void __cdecl multiverso::lightlda::Config::Init(int,char * * const)" (?Init@Config@lightlda@multiverso@@saxhqeapead@Z)
infer.obj : error LNK2001: unresolved external symbol "public: static int multiverso::lightlda::Config::num_blocks" (?num_blocks@Config@lightlda@multiverso@@2ha)
infer.obj : error LNK2001: unresolved external symbol "public: static int multiverso::lightlda::Config::num_local_workers" (?num_local_workers@Config@lightlda@multiverso@@2ha)
infer.obj : error LNK2001: unresolved external symbol "public: void __cdecl multiverso::lightlda::Document::GetDocTopicVector(class multiverso::Row &)" (?GetDocTopicVector@Document@lightlda@multiverso@@qeaaxaeav?$Row@H@3@@z)
infer.obj : error LNK2001: unresolved external symbol "public: static int multiverso::lightlda::Config::num_topics" (?num_topics@Config@lightlda@multiverso@@2ha)
infer.obj : error LNK2001: unresolved external symbol "class multiverso::lightlda::IDataStream * __cdecl multiverso::lightlda::CreateDataStream(void)" (?CreateDataStream@lightlda@multiverso@@yapeavidatastream@12@XZ)
infer.obj : error LNK2001: unresolved external symbol "public: void __cdecl multiverso::lightlda::Meta::Init(void)" (?Init@Meta@lightlda@multiverso@@qeaaxxz)
infer.obj : error LNK2001: unresolved external symbol "public: __cdecl multiverso::lightlda::Meta::~Meta(void)" (??1Meta@lightlda@multiverso@@qeaa@XZ)
infer.obj : error LNK2001: unresolved external symbol "public: __cdecl multiverso::lightlda::Meta::Meta(void)" (??0Meta@lightlda@multiverso@@qeaa@XZ)
infer.obj : error LNK2001: unresolved external symbol "public: static bool multiverso::lightlda::Config::inference" (?inference@Config@lightlda@multiverso@@2_NA)
inferer.obj : error LNK2001: unresolved external symbol "public: int __cdecl multiverso::lightlda::LightDocSampler::SampleOneDoc(class multiverso::lightlda::Document *,int,int,class multiverso::lightlda::ModelBase *,class multiverso::lightlda::AliasTable *)" (?SampleOneDoc@LightDocSampler@lightlda@multiverso@@qeaahpeavdocument@23@HHPEAVModelBase@23@PEAVAliasTable@23@@z)
inferer.obj : error LNK2001: unresolved external symbol "public: __cdecl multiverso::lightlda::LightDocSampler::LightDocSampler(void)" (??0LightDocSampler@lightlda@multiverso@@qeaa@XZ)
inferer.obj : error LNK2001: unresolved external symbol "public: void __cdecl multiverso::lightlda::AliasTable::Clear(void)" (?Clear@AliasTable@lightlda@multiverso@@qeaaxxz)
inferer.obj : error LNK2001: unresolved external symbol "public: int __cdecl multiverso::lightlda::AliasTable::Build(int,class multiverso::lightlda::ModelBase *)" (?Build@AliasTable@lightlda@multiverso@@qeaahhpeavmodelbase@23@@z)
inferer.obj : error LNK2001: unresolved external symbol "public: void __cdecl multiverso::lightlda::AliasTable::Init(class multiverso::lightlda::AliasTableIndex *)" (?Init@AliasTable@lightlda@multiverso@@qeaaxpeavaliastableindex@23@@z)
C:\Users\nguyen\Desktop\LightLDA\windows\x64\Release\infer.exe : fatal error LNK1120: 21 unresolved externals

Can anyone help me, i build infer project in VS 2017
