### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by loveJasmine** [Microsoft/LightLDA#44]
mldl@mldlUB1604:/media/mldl/data1t/ub16_prj/LightLDA$ sudo bash build.sh 
[sudo] password for mldl: 
Cloning into 'multiverso'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
build.sh: line 5: cd: multiverso: No such file or directory
build.sh: line 6: cd: third_party: No such file or directory
sh: 0: Can't open install.sh
Makefile:6: *** Makefile.config not found. See Makefile.config.example..  Stop.
make: *** No targets specified and no makefile found.  Stop.
mldl@mldlUB1604:/media/mldl/data1t/ub16_prj/LightLDA$

**Comment by dianegal** [comment]
I have faced the same difficulty as above. Has any solution been found/proposed. Appreciated if any input could be provided.

**Comment by feiga** [comment]
This is a github issue. You shall config the publickey of your github account. But the following way should also work.

Try to change the first line of build.sh from 

git clone -b multiverso-initial git@github.com:Microsoft/multiverso.git

to 

git clone -b multiverso-initial https://github.com/Microsoft/multiverso
