### ISSUE TITLE
how can i dump the model to the specified directory?

### ISSUE THREAD

**Issue by shinesun130** [Microsoft/LightLDA#46]
hi ,
I want to save the lightlda model to the specified directory. And i have found the code to dump model 
<img width="506" alt="458073ce-207b-4724-82a8-7d850cd2d5a1" src="https://cloud.githubusercontent.com/assets/26108671/23451177/cdf1fd12-fe99-11e6-814d-2969425c1513.png">

how can i parse the "output model dir" argument to this method when i train lightlda? 
Thanks very much!

**Comment by feiga** [comment]
In current implementation it can't. You may need to make modification to the code.

**Comment by shinesun130** [comment]
Thank you for reply,  I found that maybe communicator can parse the config of lightlda to server, but only found "new Server(...)" in MPI version in some condition, am i right ?


How can I parse the config without MPI version to server? hope the reply.

**Comment by shinesun130** [comment]
Thank you for reply,  I found that maybe communicator can parse the config of lightlda to server, but only found "new Server(...)" in MPI version in some condition, am i right ?
<img width="669" alt="ae95f881-75d8-4dc7-9774-53285a8dd394" src="https://cloud.githubusercontent.com/assets/26108671/23489492/af8279ee-ff2d-11e6-8596-42e29ccb7382.png">

How can I parse the config from lightlda without MPI version to server? Thank you.
