### ISSUE TITLE
Evaluation questions

### ISSUE THREAD

**Issue by thtb** [Microsoft/LightLDA#49]
![image](https://cloud.githubusercontent.com/assets/3183476/24187398/b6cdebda-0f17-11e7-876e-b7440f8cc0bd.png)
![image](https://cloud.githubusercontent.com/assets/3183476/24187416/c9f06012-0f17-11e7-9417-9e860d4d41ab.png)

should add "TrainerId() == 0" when logging ”doc likelihood“ and “word likelihood“?

**Comment by feiga** [comment]
No, the ```barrier_->Wait()``` returns true only when the last thread reach the barrier, so only one thread will satisfies this if statement and print the log.

**Comment by thtb** [comment]
I ignore that before, thanks!
