### ISSUE TITLE
the code to save the topic-word distributin with file "server_0_table_0.model" is  in which file?@feiga

### ISSUE THREAD

**Issue by qinghua2016** [Microsoft/LightLDA#52]
The model file is saved in the file multiverso/src/multiverso/server.cpp with the function DumpModel() of line 408.

**Comment by feiga** [comment]
See https://github.com/Microsoft/Multiverso/blob/9ed99cd2d3080a8683d1c511de5927e2b7274438/src/multiverso/server.cpp#L410
