### ISSUE TITLE
build failed on ubuntu14.04  --ubgpu@ubgpu:~/github/DMTK.io/lightlda$ sudo make -j4

### ISSUE THREAD

**Issue by andyyuan78** [Microsoft/lightlda#6]
g++ -O3 -std=c++11 -Wall -Wno-sign-compare -fno-omit-frame-pointer /home/ubgpu/github/DMTK.io/lightlda/preprocess/dump_binary.cpp -o /home/ubgpu/github/DMTK.io/lightlda/bin/dump_binary
/home/ubgpu/github/DMTK.io/lightlda/src/data_stream.cpp: In constructor ‘multiverso::lightlda::DiskDataStream::DiskDataStream(int32_t, std::string, int32_t)’:
/home/ubgpu/github/DMTK.io/lightlda/src/data_stream.cpp:54:21: warning: ‘multiverso::lightlda::DiskDataStream::data_path_’ will be initialized after [-Wreorder]
         std::string data_path_;
                     ^
/home/ubgpu/github/DMTK.io/lightlda/src/data_stream.cpp:52:17: warning:   ‘int32_t multiverso::lightlda::DiskDataStream::num_iterations_’ [-Wreorder]
         int32_t num_iterations_;
                 ^
/home/ubgpu/github/DMTK.io/lightlda/src/data_stream.cpp:98:5: warning:   when initialized here [-Wreorder]
     DiskDataStream::DiskDataStream(int32_t num_blocks,
     ^
g++ /home/ubgpu/github/DMTK.io/lightlda/src/lightlda.o /home/ubgpu/github/DMTK.io/lightlda/src/alias_table.o /home/ubgpu/github/DMTK.io/lightlda/src/meta.o /home/ubgpu/github/DMTK.io/lightlda/src/sampler.o /home/ubgpu/github/DMTK.io/lightlda/src/eval.o /home/ubgpu/github/DMTK.io/lightlda/src/common.o /home/ubgpu/github/DMTK.io/lightlda/src/trainer.o /home/ubgpu/github/DMTK.io/lightlda/src/data_block.o /home/ubgpu/github/DMTK.io/lightlda/src/document.o /home/ubgpu/github/DMTK.io/lightlda/src/data_stream.o -O3 -std=c++11 -Wall -Wno-sign-compare -fno-omit-frame-pointer -I/home/ubgpu/github/DMTK.io/lightlda/multiverso/include -L/home/ubgpu/github/DMTK.io/lightlda/multiverso/lib -lmultiverso -L/home/ubgpu/github/DMTK.io/lightlda/multiverso/third_party/lib -lzmq -lmpich -lmpl -o /home/ubgpu/github/DMTK.io/lightlda/bin/lightlda
/usr/bin/ld: /home/ubgpu/github/DMTK.io/lightlda/multiverso/third_party/lib/libmpich.a(ch3_win_fns.o): undefined reference to symbol 'pthread_mutexattr_init@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [/home/ubgpu/github/DMTK.io/lightlda/bin/lightlda] Error 1
make: *** Waiting for unfinished jobs....

**Comment by feiga** [comment]
@andyyuan78 

Please try add ```-pthread``` in line 17 in Makefile

```LD_FLAGS += -L$(THIRD_PARTY_LIB) -lzmq -lmpich -lmpl -pthread```

We tested on Ubuntu 12.04 and didn't encounter such problems. I'm still not clear why.

**Comment by cldellow** [comment]
I had this issue and can confirm that adding `-pthread` solved it.

**Comment by chivee** [comment]
@feiga  i think we should fix this in the Makefile

**Comment by andyyuan78** [comment]
@feiga thanks, it fixed
