### ISSUE TITLE
How can i use the result to train a topic model

### ISSUE THREAD

**Issue by ruskie95** [Microsoft/LightLDA#61]
I am a studen. I have just learned about machine learning. How can i use the doc_topic , server_0_table_0 (word_topic table) and server_0_table_1 to train and test a model. The model is trainned for  Text Classifcation which i can use it to auto-recognize the topic of newspapers
Thank you!

**Comment by 1234clam** [comment]
there is a infer executable file in the bin directory and you can run the file by fellow command:
```
$bin/infer -num_vocabs 111400 -num_topics 1000 -num_iterations 100 -alpha 0.1 -beta 0.01 -mh_steps 2 -num_local_workers 1 -num_blocks 1 -max_num_document 300000 -input_dir $dir -data_capacity 800
```
it will get the result in  doc_topic.0 file contain the inference result. Before run the infer you should put the server_0_table_1.model server_0_table_0.model block.0 vocab.0 vocab.0.txt in the input directory.
I hope this answer can help you to solve this question.

**Comment by ruskie95** [comment]
![image](https://user-images.githubusercontent.com/33618335/32828549-ff435e16-ca21-11e7-9681-12d34a6a9960.png)
i build infer by VS but get some error, u have anything ideal about thí. I already add mutilverso.lib

**Comment by ruskie95** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __cdecl multiverso::lightlda::AliasTable::AliasTable(void)" (??0AliasTable@lightlda@multiverso@@QEAA@XZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: static bool multiverso::lightlda::Config::warm_start" (?warm_start@Config@lightlda@multiverso@@2_NA)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK1120	21 unresolved externals	infer	C:\Users\nguyen\Desktop\LightLDA\windows\x64\Release\infer.exe	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl multiverso::lightlda::AliasTable::Init(class multiverso::lightlda::AliasTableIndex *)" (?Init@AliasTable@lightlda@multiverso@@QEAAXPEAVAliasTableIndex@23@@Z)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\inferer.obj	1	
Error	LNK2001	unresolved external symbol "public: int __cdecl multiverso::lightlda::AliasTable::Build(int,class multiverso::lightlda::ModelBase *)" (?Build@AliasTable@lightlda@multiverso@@QEAAHHPEAVModelBase@23@@Z)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\inferer.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl multiverso::lightlda::AliasTable::Clear(void)" (?Clear@AliasTable@lightlda@multiverso@@QEAAXXZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\inferer.obj	1	
Error	LNK2001	unresolved external symbol "public: int __cdecl multiverso::lightlda::LightDocSampler::SampleOneDoc(class multiverso::lightlda::Document *,int,int,class multiverso::lightlda::ModelBase *,class multiverso::lightlda::AliasTable *)" (?SampleOneDoc@LightDocSampler@lightlda@multiverso@@QEAAHPEAVDocument@23@HHPEAVModelBase@23@PEAVAliasTable@23@@Z)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\inferer.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl multiverso::lightlda::LightDocSampler::LightDocSampler(void)" (??0LightDocSampler@lightlda@multiverso@@QEAA@XZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\inferer.obj	1	
Error	LNK2001	unresolved external symbol "public: static bool multiverso::lightlda::Config::inference" (?inference@Config@lightlda@multiverso@@2_NA)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl multiverso::lightlda::Meta::Meta(void)" (??0Meta@lightlda@multiverso@@QEAA@XZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl multiverso::lightlda::Meta::~Meta(void)" (??1Meta@lightlda@multiverso@@QEAA@XZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl multiverso::lightlda::Meta::Init(void)" (?Init@Meta@lightlda@multiverso@@QEAAXXZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "class multiverso::lightlda::IDataStream * __cdecl multiverso::lightlda::CreateDataStream(void)" (?CreateDataStream@lightlda@multiverso@@YAPEAVIDataStream@12@XZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: static int multiverso::lightlda::Config::num_topics" (?num_topics@Config@lightlda@multiverso@@2HA)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl multiverso::lightlda::Document::GetDocTopicVector(class multiverso::Row<int> &)" (?GetDocTopicVector@Document@lightlda@multiverso@@QEAAXAEAV?$Row@H@3@@Z)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: static int multiverso::lightlda::Config::num_local_workers" (?num_local_workers@Config@lightlda@multiverso@@2HA)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: static int multiverso::lightlda::Config::num_blocks" (?num_blocks@Config@lightlda@multiverso@@2HA)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: static void __cdecl multiverso::lightlda::Config::Init(int,char * * const)" (?Init@Config@lightlda@multiverso@@SAXHQEAPEAD@Z)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl multiverso::lightlda::LocalModel::LocalModel(class multiverso::lightlda::Meta *)" (??0LocalModel@lightlda@multiverso@@QEAA@PEAVMeta@12@@Z)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl multiverso::lightlda::LocalModel::Init(void)" (?Init@LocalModel@lightlda@multiverso@@QEAAXXZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: static int multiverso::lightlda::Config::num_iterations" (?num_iterations@Config@lightlda@multiverso@@2HA)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl multiverso::lightlda::AliasTable::~AliasTable(void)" (??1AliasTable@lightlda@multiverso@@QEAA@XZ)	infer	C:\Users\nguyen\Desktop\LightLDA\windows\infer\infer.obj	1

**Comment by ruskie95** [comment]
Do you have any ideal i can use those file for WEKA to build a model.It seems incompatible with each other.

**Comment by 1234clam** [comment]
@ruskie95 
```
https://github.com/Microsoft/LightLDA/issues/60
```
